### PR TITLE
Make the airbnb config a peer dependency for npm3 support

### PR DESCRIPTION
**Pull request by jkimbo**
Follow up pr in lystable-frontend to add `eslint-config-airbnb` to dev dependencies

### CODE REVIEW

**Comment by Chrisui** [comment]
Do we need to change where ["extends" in index.js](https://github.com/lystable/guidelines/blob/master/styleguides/eslint-config-lystable/index.js#L4) is pointing?

**Comment by jkimbo** [comment]
@Chrisui good catch!

**Comment by jkimbo** [comment]
@Chrisui updated and tested locally

**Comment by Chrisui** [comment]
:+1:

**Pull request merged**
